blueprint:
  name: Trigger for lysstyring Beta
  description: >
    Dette er første del av lysstyringen. Det er en automasjon som ved bevegelse får en input_boolean til å slå seg på. Etter en gitt tid uten aktivitet slår den verdien av igjen.

    For at dette skal fungere må scener aktiveres av denne verdien.

  domain: automation
  author: Karl Jørgen
  source_url: https://github.com/karlalskens/Home-Assistant-Lysstyring/blob/main/blueprints/automation/karlalskens_Lysstyring/Trigger_for_Lysstyring_beta.yaml
  input:
    omraade_section:
      name: Område
      icon: mdi:map-marker
      description: Her setter du opp hvilket område av huset som skal styres. Det kan være et rom, eller en del av et større rom.
      input:
        input_booleans:
          name: Velg område
          description: Angi hjelpeverdien for området. Må være en input_boolean som begynner med "tilstede_". Har du ikke en fra før, kan du opprette en.
          selector:
            entity:
              domain: input_boolean
              multiple: false
        bypass_boolean:
          name: Velg Variabel som deaktiverer tidsstyringen
          description: Hvilken hjelpeverdi skal brukes til å deaktivere styringen?
          selector:
            entity:
              domain: input_boolean
              multiple: false
    sensorer_section:
      name: Sensorer og tid
      icon: mdi:motion-sensor
      description: Her setter du opp hvilket område av huset som skal styres. Det kan være et rom, eller en del av et større rom.
      input:
        binary_sensors:
          name: Bevegelsessensorer
          description: Hvilke bevegelsessensorer skal brukes som triggere?
          selector:
            entity:
              domain: binary_sensor
              multiple: true
        countdown_time:
          name: Velg tid
          description: Hvor lang tid skal det ta før lyset skal slukkes?
          selector:
            duration: {}
    my_section:
      name: Scener
      icon: mdi:palette
      description: Vel scenene som skal brukes til lysstyringen
      input:
        scene_dagtid_aktiv:
          name: Dagtid Aktiv
          description: Når det er dagslys og lyset skal slås på.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_dagtid_passiv:
          name: Dagtid Passiv
          description: Når det er dagslys og lyset skal slås av.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_kveldstid_aktiv:
          name: Kveldstid Aktiv
          description: Når det er kveld/natt og lyset skal slås på.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_kveldstid_passiv:
          name: Kveldstid Passiv
          description: Når det er kveld/natt ute og lyset skal slås av.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_natt_aktiv:
          name: Nattlys Aktiv
          description: Når det er natt og lyset skal slås på lavt.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
trigger:
  - platform: state
    entity_id: !input binary_sensors
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input input_booleans
    from: "on"
    to: "off"
condition:
  - condition: state
    entity_id: !input bypass_boolean
    state: "off"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' and trigger.from_state.state == 'off' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input input_booleans
          - delay: !input countdown_time
          - repeat:
              while:
                - condition: template
                  value_template: >-
                    {% set sensors = expand(binary_sensors) %}
                    {{ not sensors | selectattr('state', 'eq', 'on') | list | length > 0 }}
              sequence:
                - delay: !input countdown_time
  - choose:
      - conditions:
          - condition: state
            entity_id: !input input_booleans
            state: "off"
        sequence: []
    default:
      - service: input_boolean.turn_off
        target:
          entity_id: !input input_booleans
mode: restart